name = "Astrometry"
uuid = "f1a567a2-b8c3-46a6-a8e4-0d50b742dea6"
authors = ["Paul Barrett <pebarrett@gmail.com> and contributors"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticUnivariatePolynomials = "6f584044-cad5-5b68-a429-1e244a824f76"

[compat]
StaticArrays = "1.9"
StaticUnivariatePolynomials = "<1.0"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
